[package]
name = "paprika-cli"
description = "Reflow PDFs for small screens"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish = false

[lints]
workspace = true

[[bin]]
name = "paprika"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
paprika-core = { version = "0.1.0", path = "../paprika-core" }
paprika-epub = { version = "0.1.0", path = "../paprika-epub" }
paprika-pdf = { version = "0.1.0", path = "../paprika-pdf" }
