[package]
name = "paprika-cli"
description = "Reflow PDFs for small screens"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "paprika"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
paprika-core = { path = "../paprika-core" }
paprika-pdf = { path = "../paprika-pdf" }
